language: python
python:
  - "3.7"

branches:
  only:
  - master
  - develop
  - /^release[/-].*$/
  - travis-test

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e .[tests]

script:
  - python -m pytest -ra

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: iconfoundation
  password: $PYPI_PW
  on:
    branch: master
