language: python
python:
  - "3.7"

branches:
  only:
  - master
  - develop
  - /^release[/-].*$/
  - /^feature\/.*$/
  - travis-test

install:
  - pip install -r requirements.txt
  - make generate-proto

script:
  - python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: iconfoundation
  password: $PYPI_PW
  on:
    branch: master
